### PR TITLE
removed some old code should be working now

### PR DESCRIPTION
**Pull request by passie**

### CODE REVIEW

**Comment by assaflavie** [comment]
I suggest you use `docker inspect` to look for the extra hosts, and not `exec`.

**Comment by passie** [comment]
The problem is that the hosts doesn't have to be in the hostconfig ?

**Comment by assaflavie** [comment]
Well, if they're not there then they're probably in the image itself, right? In which case the user will still get them with `runlike`. On the other hand, I don't think you can assume that anything in the hosts file of a container you want to be added with `--add-host`.

**Comment by passie** [comment]
Will do some re-work in the future.

**Pull request closed without merging**
